{
 "title": "JWT Pizza",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "revenue_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "revenue"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_latency_milliseconds_total{source=\"jwt-pizza-service\"}[20s])",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(request_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizza_purchases_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(purchase_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(failure_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "active_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by(source) (rate(requests_total{source=\"jwt-pizza-service-dev\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[DELETE] /api/auth\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[GET] /api/order/menu\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[POST] /api/order\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(requests_total{endpoint=\"[PUT] /api/auth\"}[1m])",
     "legendFormat": "put"
    }
   ]
  }
 ]
}